#!/bin/bash
# Script for ChaosSquirrel

SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

echo "Executing all Scripts ..."
find "${SCRIPT_DIR}" -iname \*.sh -exec \{\} \; 
